import fs from 'fs';
import path from 'path';
import { glob } from 'glob';
import matter from 'gray-matter';

interface BlogPostMeta {
  slug: string;
  title: string;
  date: string;
  category: string;
  readTime: string;
}

async function generateManifest() {
  const postsDir = path.join(process.cwd(), 'src/content/posts');
  const outputPath = path.join(process.cwd(), 'src/generated/blog-manifest.ts');

  // Ensure directories exist
  if (!fs.existsSync(postsDir)) {
    fs.mkdirSync(postsDir, { recursive: true });
  }

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Find all MDX files
  const files = await glob('*.mdx', { cwd: postsDir });

  const posts: BlogPostMeta[] = [];

  for (const file of files) {
    const filePath = path.join(postsDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { data } = matter(content);

    const slug = file.replace('.mdx', '');

    posts.push({
      slug,
      title: data.title || slug,
      date: data.date || '',
      category: data.category || 'UNCATEGORIZED',
      readTime: data.readTime || '5 MIN',
    });
  }

  // Sort by date descending
  posts.sort((a, b) => {
    const dateA = a.date.replace(/\./g, '');
    const dateB = b.date.replace(/\./g, '');
    return dateB.localeCompare(dateA);
  });

  // Generate TypeScript file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-blog-manifest.ts

import type { BlogPost } from '@/types/blog';

export const blogManifest: Omit<BlogPost, 'id' | 'content'>[] = ${JSON.stringify(posts, null, 2)};

export const getPostBySlug = (slug: string) =>
  blogManifest.find(post => post.slug === slug);

export const getAllSlugs = () =>
  blogManifest.map(post => post.slug);
`;

  fs.writeFileSync(outputPath, output);
  console.log(`Generated blog manifest with ${posts.length} posts`);
}

generateManifest().catch(console.error);
