import fs from 'fs';
import path from 'path';
import { glob } from 'glob';
import matter from 'gray-matter';

interface SpiritualPostMeta {
  slug: string;
  title: string;
  subtitle?: string;
  category: 'reflection' | 'practice' | 'philosophy';
  date: string;
  readTime: string;
  featured?: boolean;
}

async function generateManifest() {
  const contentDir = path.join(process.cwd(), 'src/content/spiritual');
  const outputPath = path.join(process.cwd(), 'src/generated/spiritual-manifest.ts');

  // Ensure directory exists
  if (!fs.existsSync(contentDir)) {
    fs.mkdirSync(contentDir, { recursive: true });
  }

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Find all MDX files
  const files = await glob('*.mdx', { cwd: contentDir });

  const posts: SpiritualPostMeta[] = [];

  for (const file of files) {
    const filePath = path.join(contentDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { data } = matter(content);

    const slug = file.replace('.mdx', '');

    posts.push({
      slug,
      title: data.title || slug,
      subtitle: data.subtitle || undefined,
      category: data.category || 'reflection',
      date: data.date || new Date().toISOString().split('T')[0].replace(/-/g, '.'),
      readTime: data.readTime || '5 MIN',
      featured: data.featured || false,
    });
  }

  // Sort by date descending, featured first
  posts.sort((a, b) => {
    if (a.featured && !b.featured) return -1;
    if (!a.featured && b.featured) return 1;
    const dateA = a.date.replace(/\./g, '');
    const dateB = b.date.replace(/\./g, '');
    return dateB.localeCompare(dateA);
  });

  // Generate TypeScript file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-spiritual-manifest.ts

import type { SpiritualPost } from '@/types/spiritual';

export const spiritualManifest: SpiritualPost[] = ${JSON.stringify(posts, null, 2)};

export const getPostBySlug = (slug: string) =>
  spiritualManifest.find(post => post.slug === slug);

export const getFeaturedPosts = () =>
  spiritualManifest.filter(post => post.featured);

export const getAllSlugs = () =>
  spiritualManifest.map(post => post.slug);
`;

  fs.writeFileSync(outputPath, output);
  console.log(`Generated spiritual manifest with ${posts.length} posts`);
}

generateManifest().catch(console.error);
